# Generated by Django 4.2.7 on 2025-09-23 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseJurisprudenciaTese',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tese_juridica', models.TextField(verbose_name='Tese jurídica analisada')),
                ('termos_busca', models.JSONField(default=list, verbose_name='Termos de busca utilizados')),
                ('filtros_aplicados', models.JSONField(default=dict, verbose_name='Filtros aplicados na busca')),
                ('periodo_analise_inicio', models.DateField(verbose_name='Início do período analisado')),
                ('periodo_analise_fim', models.DateField(verbose_name='Fim do período analisado')),
                ('total_julgados_encontrados', models.IntegerField(default=0, verbose_name='Total de julgados encontrados')),
                ('total_julgados_favoraveis', models.IntegerField(default=0, verbose_name='Total de julgados favoráveis')),
                ('percentual_favorabilidade', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual de favorabilidade')),
                ('argumentos_favoraveis', models.JSONField(default=list, verbose_name='Principais argumentos favoráveis')),
                ('precedentes_fortes', models.JSONField(default=list, verbose_name='Precedentes de tribunais superiores')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações da análise')),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='processando', max_length=20, verbose_name='Status')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Análise de Jurisprudência - Tese',
                'verbose_name_plural': 'Análises de Jurisprudência - Teses',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Julgado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero_processo', models.CharField(max_length=50, verbose_name='Número do processo')),
                ('titulo', models.TextField(verbose_name='Título/Ementa')),
                ('conteudo', models.TextField(verbose_name='Conteúdo completo do julgado')),
                ('data_publicacao', models.DateField(verbose_name='Data de publicação')),
                ('tribunal', models.CharField(max_length=100, verbose_name='Tribunal')),
                ('vara', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vara')),
                ('comarca', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comarca')),
                ('relator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Relator')),
                ('djen_id', models.CharField(max_length=100, unique=True, verbose_name='ID no DJEN')),
                ('url_original', models.URLField(blank=True, null=True, verbose_name='URL original')),
                ('processado', models.BooleanField(default=False, verbose_name='Processado pelos agentes')),
                ('hash_conteudo', models.CharField(db_index=True, max_length=64, verbose_name='Hash do conteúdo')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Julgado',
                'verbose_name_plural': 'Julgados',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='PadroesVaraTribunal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tribunal', models.CharField(max_length=100, verbose_name='Tribunal')),
                ('vara', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vara específica')),
                ('tema_juridico', models.TextField(verbose_name='Tema jurídico analisado')),
                ('periodo_analise_inicio', models.DateField(verbose_name='Início do período analisado')),
                ('periodo_analise_fim', models.DateField(verbose_name='Fim do período analisado')),
                ('total_julgados_analisados', models.IntegerField(default=0, verbose_name='Total de julgados analisados')),
                ('padroes_julgamento', models.JSONField(default=dict, verbose_name='Padrões de julgamento identificados')),
                ('perfil_julgador', models.JSONField(default=dict, verbose_name='Perfil do julgador/órgão')),
                ('precedentes_citados', models.JSONField(default=list, verbose_name='Precedentes mais citados')),
                ('valores_indenizacao', models.JSONField(default=dict, verbose_name='Estatísticas de valores (se aplicável)')),
                ('teses_aceitas', models.JSONField(default=list, verbose_name='Teses frequentemente aceitas')),
                ('teses_rejeitadas', models.JSONField(default=list, verbose_name='Teses frequentemente rejeitadas')),
                ('comparacao_outros_orgaos', models.JSONField(default=dict, verbose_name='Comparação com outros órgãos')),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='processando', max_length=20, verbose_name='Status')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('julgados_analisados', models.ManyToManyField(related_name='padroes_vara', to='jurisprudencia.julgado', verbose_name='Julgados analisados')),
            ],
            options={
                'verbose_name': 'Padrões de Vara/Tribunal',
                'verbose_name_plural': 'Padrões de Varas/Tribunais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='JulgadoFavoravel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('score_favorabilidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score de favorabilidade (0-100)')),
                ('justificativa', models.TextField(verbose_name='Justificativa do score')),
                ('eh_precedente_forte', models.BooleanField(default=False, verbose_name='É precedente forte')),
                ('argumentos_chave', models.JSONField(default=list, verbose_name='Argumentos-chave identificados')),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurisprudencia.analisejurisprudenciatese')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('julgado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurisprudencia.julgado')),
            ],
            options={
                'verbose_name': 'Julgado Favorável',
                'verbose_name_plural': 'Julgados Favoráveis',
            },
        ),
        migrations.CreateModel(
            name='EstrategiaAntecipatoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero_processo', models.CharField(max_length=50, verbose_name='Número do processo')),
                ('tribunal_destino', models.CharField(max_length=100, verbose_name='Tribunal/vara de destino')),
                ('vara_destino', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vara específica')),
                ('documentos_caso', models.JSONField(default=list, verbose_name='Documentos do caso analisados')),
                ('resumo_caso', models.TextField(verbose_name='Resumo do caso')),
                ('probabilidade_sucesso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Probabilidade de sucesso (%)')),
                ('riscos_identificados', models.JSONField(default=list, verbose_name='Riscos específicos identificados')),
                ('estrategias_mitigacao', models.JSONField(default=list, verbose_name='Estratégias de mitigação')),
                ('argumentos_direcionados', models.JSONField(default=list, verbose_name='Argumentos direcionados para o órgão')),
                ('precedentes_recomendados', models.JSONField(default=list, verbose_name='Precedentes recomendados para citação')),
                ('pontos_atencao', models.JSONField(default=list, verbose_name='Pontos de atenção específicos')),
                ('cronograma_recomendado', models.JSONField(default=dict, verbose_name='Cronograma recomendado')),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='processando', max_length=20, verbose_name='Status')),
                ('resultado_real', models.CharField(blank=True, choices=[('favoravel', 'Favorável'), ('desfavoravel', 'Desfavorável'), ('parcial', 'Parcialmente favorável'), ('pendente', 'Pendente')], max_length=20, null=True, verbose_name='Resultado real')),
                ('data_resultado', models.DateField(blank=True, null=True, verbose_name='Data do resultado')),
                ('observacoes_resultado', models.TextField(blank=True, null=True, verbose_name='Observações sobre o resultado')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('padrao_vara_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estrategias_baseadas', to='jurisprudencia.padroesvaratribunal', verbose_name='Padrão de vara relacionado')),
            ],
            options={
                'verbose_name': 'Estratégia Antecipatória',
                'verbose_name_plural': 'Estratégias Antecipatórias',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='analisejurisprudenciatese',
            name='julgados_favoraveis',
            field=models.ManyToManyField(related_name='analises_favoraveis', through='jurisprudencia.JulgadoFavoravel', to='jurisprudencia.julgado', verbose_name='Julgados favoráveis'),
        ),
        migrations.CreateModel(
            name='AnaliseJurisprudenciaNeutra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tema_juridico', models.TextField(verbose_name='Tema jurídico analisado')),
                ('filtros_aplicados', models.JSONField(default=dict, verbose_name='Filtros aplicados na busca')),
                ('periodo_analise_inicio', models.DateField(verbose_name='Início do período analisado')),
                ('periodo_analise_fim', models.DateField(verbose_name='Fim do período analisado')),
                ('total_julgados_analisados', models.IntegerField(default=0, verbose_name='Total de julgados analisados')),
                ('julgados_favoraveis', models.IntegerField(default=0, verbose_name='Julgados favoráveis ao tema')),
                ('julgados_contrarios', models.IntegerField(default=0, verbose_name='Julgados contrários ao tema')),
                ('julgados_neutros', models.IntegerField(default=0, verbose_name='Julgados neutros')),
                ('tendencia_majoritaria', models.CharField(choices=[('favoravel', 'Favorável'), ('contraria', 'Contrária'), ('dividida', 'Dividida'), ('neutra', 'Neutra')], max_length=20, verbose_name='Tendência majoritária')),
                ('argumentos_pro', models.JSONField(default=list, verbose_name='Principais argumentos pró')),
                ('argumentos_contra', models.JSONField(default=list, verbose_name='Principais argumentos contra')),
                ('evolucao_temporal', models.JSONField(default=dict, verbose_name='Evolução da tendência no tempo')),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='processando', max_length=20, verbose_name='Status')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('julgados_representativos', models.ManyToManyField(related_name='analises_neutras', to='jurisprudencia.julgado', verbose_name='Julgados representativos')),
            ],
            options={
                'verbose_name': 'Análise de Jurisprudência - Neutra',
                'verbose_name_plural': 'Análises de Jurisprudência - Neutras',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='padroesvaratribunal',
            index=models.Index(fields=['tribunal', 'vara'], name='jurispruden_tribuna_71a602_idx'),
        ),
        migrations.AddIndex(
            model_name='padroesvaratribunal',
            index=models.Index(fields=['status', 'criado_em'], name='jurispruden_status_7f4315_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='padroesvaratribunal',
            unique_together={('tribunal', 'vara', 'tema_juridico', 'periodo_analise_inicio', 'periodo_analise_fim')},
        ),
        migrations.AddIndex(
            model_name='julgadofavoravel',
            index=models.Index(fields=['score_favorabilidade'], name='jurispruden_score_f_1ac944_idx'),
        ),
        migrations.AddIndex(
            model_name='julgadofavoravel',
            index=models.Index(fields=['eh_precedente_forte'], name='jurispruden_eh_prec_b4731f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='julgadofavoravel',
            unique_together={('analise', 'julgado')},
        ),
        migrations.AddIndex(
            model_name='julgado',
            index=models.Index(fields=['tribunal', 'data_publicacao'], name='jurispruden_tribuna_73bfe7_idx'),
        ),
        migrations.AddIndex(
            model_name='julgado',
            index=models.Index(fields=['numero_processo'], name='jurispruden_numero__ef2dff_idx'),
        ),
        migrations.AddIndex(
            model_name='julgado',
            index=models.Index(fields=['djen_id'], name='jurispruden_djen_id_d52f65_idx'),
        ),
        migrations.AddIndex(
            model_name='julgado',
            index=models.Index(fields=['hash_conteudo'], name='jurispruden_hash_co_5dd771_idx'),
        ),
        migrations.AddIndex(
            model_name='estrategiaantecipatoria',
            index=models.Index(fields=['tribunal_destino', 'vara_destino'], name='jurispruden_tribuna_2bb514_idx'),
        ),
        migrations.AddIndex(
            model_name='estrategiaantecipatoria',
            index=models.Index(fields=['probabilidade_sucesso'], name='jurispruden_probabi_83243a_idx'),
        ),
        migrations.AddIndex(
            model_name='estrategiaantecipatoria',
            index=models.Index(fields=['status', 'criado_em'], name='jurispruden_status_9bdbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='estrategiaantecipatoria',
            index=models.Index(fields=['resultado_real'], name='jurispruden_resulta_9ef84d_idx'),
        ),
        migrations.AddIndex(
            model_name='analisejurisprudenciatese',
            index=models.Index(fields=['status', 'criado_em'], name='jurispruden_status_e7b978_idx'),
        ),
        migrations.AddIndex(
            model_name='analisejurisprudenciatese',
            index=models.Index(fields=['percentual_favorabilidade'], name='jurispruden_percent_50f459_idx'),
        ),
        migrations.AddIndex(
            model_name='analisejurisprudencianeutra',
            index=models.Index(fields=['status', 'criado_em'], name='jurispruden_status_a9bf90_idx'),
        ),
        migrations.AddIndex(
            model_name='analisejurisprudencianeutra',
            index=models.Index(fields=['tendencia_majoritaria'], name='jurispruden_tendenc_3d322c_idx'),
        ),
    ]
